### ISSUE TITLE
Migrate from Forward to Function

### ISSUE THREAD

**Issue by CrazyHackGUT** [CrazyHackGUT/sm-ripext#4]
We can call `IPluginFunction` directly. Why we create `IChangeableForward`?

**Comment by peace-maker** [comment]
Because you'd have to keep track of the plugin's lifecycle yourself to avoid crashes when the plugin gets unloaded/reloaded and the IPluginFunction pointer gets invalidated. The forwards system handles that for you and you can just check IChangeableForward::GetFunctionCount() too see if the plugin in still there.

Your change effectively introduced a new crash vector when unloading plugins while a http request is running. You should revert it.

How about creating pull requests for the other features you've added? So people don't have to look at different places for a fully working extension.

**Comment by CrazyHackGUT** [comment]
@peace-maker sometimes `IChangeableForward` pointer "converts" to null. I really don't know, why.
I has spent some time for debugging. [Here](https://github.com/ErikMinekus/sm-ripext/blob/master/extension.cpp#L115) `forward` is `null` sometimes.

> How about creating pull requests for the other features you've added?

I thought about this. But... Erik threw the extension, I guess. I do not see any activity in the repository.

**Comment by peace-maker** [comment]
Hm, you can try moving `this->callbackQueue.pop();` behind the local cache variables, so it looks like 
```cpp
struct HTTPRequestCallback &callback = this->callbackQueue.front();

IChangeableForward *forward = callback.forward;
struct HTTPResponse response = callback.response;
cell_t value = callback.value;
this->callbackQueue.pop();
```

He's still maintaining it, so he'll review pull requests for sure.
